import com.android.build.gradle.internal.tasks.CompileArtProfileTask

import java.nio.file.Paths

plugins {
    id('com.android.application')
    id('org.jetbrains.kotlin.android')
    id('org.jetbrains.kotlin.plugin.compose')
    id('dev.rikka.tools.refine')
    id('dev.rikka.tools.autoresconfig')
    id('dev.rikka.tools.materialthemebuilder')
}

android {
    namespace = 'moe.shizuku.manager'
    defaultConfig {
        applicationId "moe.shizuku.privileged.api"
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionName
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=none'
            }
        }
    }
    buildFeatures {
        buildConfig = true
        compose = true
        viewBinding = true
        prefab = true
    }
    signingConfigs {
        sign
    }
    buildTypes {
        debug {
            signingConfig = signingConfigs.sign
        }
        release {
            signingConfig = signingConfigs.sign
            minifyEnabled true
            shrinkResources = true
            vcsInfo.include = false
            proguardFiles 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
            version = "3.31.0+"
        }
    }
    kotlinOptions {
        jvmTarget = "21"
    }
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += ['**']
        }
    }
    dependenciesInfo {
        includeInApk = false
    }
    lint {
        checkReleaseBuilds = false
    }
}

autoResConfig {
    generatedClassFullName = "rikka.shizuku.manager.ShizukuLocales"
    generateRes = false
    generatedArrayFirstItem = "SYSTEM"
    generateLocaleConfig = true
}

materialThemeBuilder {
    themes {
        shizuku {
            primaryColor = "#3F51B5"
            lightThemeFormat = "Theme.Material3.Light.%s"
            lightThemeParent = "Theme.Material3.Light.Rikka"
            darkThemeFormat = "Theme.Material3.Dark.%s"
            darkThemeParent = "Theme.Material3.Dark.Rikka"
        }
    }
    generatePalette = true
    generateTextColors = true
}

def collapseReleaseResourceNames = task('collapseReleaseResourceNames').doLast {
    def aapt2 = Paths.get(project.android.sdkDirectory.path, 'build-tools', project.android.buildToolsVersion, 'aapt2')
    def zip = Paths.get(project.buildDir.path, 'intermediates',
            'optimized_processed_res', 'release', 'optimizeReleaseResources', 'resources-release-optimize.ap_')
    def optimized = new File("${zip}.opt")
    def cmd = exec {
        commandLine aapt2, 'optimize', '--collapse-resource-names',
                '--resources-config-path', 'aapt2-resources.cfg',
                '-o', optimized, zip
        ignoreExitValue false
    }
    if (cmd.exitValue == 0) {
        delete(zip)
        optimized.renameTo("$zip")
    }
}

afterEvaluate {
    tasks.getByName('optimizeReleaseResources').finalizedBy(collapseReleaseResourceNames)
    tasks.getByName('preReleaseBuild').dependsOn(':shell:assembleRelease')
    tasks.getByName('preDebugBuild').dependsOn(':shell:assembleDebug')
}

android.applicationVariants.configureEach { variant ->
    variant.outputs.configureEach {
        outputFileName = "shizuku-v${variant.versionName}-${variant.name}.apk"

        variant.assembleProvider.get().doLast {
            def outDir = new File(rootDir, "out")
            def mappingDir = new File(outDir, "mapping").absolutePath
            def apkDir = new File(outDir, "apk").absolutePath

            if (variant.getBuildType().isMinifyEnabled()) {
                copy {
                    from variant.mappingFileProvider.get()
                    into mappingDir
                    rename { String fileName -> "mapping-${variant.versionName}.txt" }
                }
                copy {
                    from outputFile
                    into apkDir
                }
            }
        }
    }
}

tasks.withType(CompileArtProfileTask.class).configureEach {
    enabled = false
}
configurations.configureEach {
    exclude group: 'androidx.appcompat', module: 'appcompat'
    exclude group: 'androidx.profileinstaller', module: 'profileinstaller'
}

dependencies {
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    implementation project(':server')
    implementation project(':common')
    implementation project(':rish')
    implementation project(':starter')
    implementation project(':api')
    implementation project(':provider')

    implementation libs.hidden.compat
    compileOnly libs.hidden.stub

    implementation libs.androidx.browser
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.activity.compose
    implementation libs.androidx.compose.ui
    implementation libs.androidx.compose.ui.tooling.preview
    implementation libs.androidx.compose.material3
    implementation libs.androidx.compose.material.icons.extended
    implementation libs.androidx.compose.runtime.livedata
    debugImplementation libs.androidx.compose.ui.tooling
    implementation libs.androidx.core.ktx
    implementation libs.androidx.fragment.ktx
    implementation libs.androidx.lifecycle.viewmodel.ktx
    implementation libs.androidx.lifecycle.livedata.ktx
    implementation libs.androidx.work.runtime.ktx

    implementation libs.google.material

    implementation libs.libsu.core

    implementation libs.appcompat
    implementation libs.compatibility
    implementation libs.rikka.core.ktx
    implementation libs.rikka.material
    implementation libs.rikka.html.ktx
    implementation libs.borderview
    implementation libs.rikka.lifecycle.resource.livedata
    implementation libs.rikka.lifecycle.shared.viewmodel
    implementation libs.rikka.lifecycle.viewmodel.lazy

    implementation libs.boringssl
    implementation libs.libcxx

    implementation libs.hiddenapibypass

    implementation libs.bouncycastle.bcpkix

    implementation libs.appiconloader
}

apply from: rootProject.file('signing.gradle')
